import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { api } from '../api/client';

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

const MESSAGES = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.branches': 'Branches',
    'nav.banks': 'Banks',
    'nav.inventory': 'Inventory',
    'nav.suppliers': 'Suppliers',
    'nav.staff': 'Staff, Salary, Rent & Bills',
    'nav.sales': 'Sales',
    'nav.receivables': 'Receivables',
    'nav.purchases': 'Purchases',
    'nav.payments': 'Payments',
    'nav.reports': 'Reports & Analytics',
    'nav.users': 'Users & Roles',
    'nav.settings': 'Settings',
    'page.dashboard.title': 'Dashboard',
    'page.branches.title': 'Branch Management',
    'page.banks.title': 'Bank Management',
    'page.inventory.title': 'Inventory',
    'page.suppliers.title': 'Suppliers',
    'page.staff.title': 'Staff, Salary, Rent & Bills',
    'page.sales.title': 'Sales Management',
    'page.receivables.title': 'Receivables (Credit Sales)',
    'page.purchases.title': 'Purchase Management',
    'page.payments.title': 'Payments',
    'page.reports.title': 'Reports & Analytics',
    'page.users.title': 'Users & Roles',
    // Dashboard cards
    'dashboard.card.salesToday': 'Sales Today',
    'dashboard.card.salesTodayCash': 'Cash Sales Today',
    'dashboard.card.salesTodayBank': 'Bank Sales Today',
    'dashboard.card.salesTodayCredit': 'Sales Today on Credit',
    'dashboard.card.salesOnCredit': 'Sales on Credit (Receivable)',
    'dashboard.card.receivableRecovered': 'Receivable Recoveries (Total)',
    'dashboard.card.salesMonth': 'Sales (Month)',
    'dashboard.card.salesMonthCash': 'Cash Sales (Month)',
    'dashboard.card.salesMonthBank': 'Bank Sales (Month)',
    'dashboard.card.netProfitMonth': 'Net Profit (Month)',
    'dashboard.card.cashInHand': 'Cash in Hand',
    'dashboard.card.bankBalance': 'Bank Balance',
    'dashboard.card.payables': 'Payables',
    'dashboard.card.rentBillsPayable': 'Total Rent & Bills Payable',
    'dashboard.card.salariesPayable': 'Total Salaries Payable',
    'dashboard.card.totalPaidAll': 'Total Paid (All)',
    // Generic column labels
    'col.code': 'Code',
    'col.name': 'Name',
    'col.location': 'Location',
    'col.manager': 'Manager',
    'col.openingClosing': 'Opening / Closing',
    'col.status': 'Status',
    'col.actions': 'Actions',
    'col.date': 'Date',
    'col.type': 'Type',
    'col.amount': 'Amount',
    'col.reference': 'Reference',
    'col.description': 'Description',
    'col.branch': 'Branch',
    'col.accountNumber': 'Account #',
    'col.balance': 'Balance',
    'col.product': 'Product',
    'col.soldQuantity': 'Sold quantity',
    'col.unitPrice': 'Unit Price',
    'col.total': 'Total',
    'col.totalQuantitySold': 'Total quantity sold',
    'col.totalAmount': 'Total amount',
    'col.address': 'Address',
    'col.phone': 'Phone',
    'col.vatNumber': 'VAT Number',
    'col.pendingBalance': 'Pending balance',
    'col.invoice': 'Invoice',
    'col.dueDate': 'Due Date',
    'col.totalPurchases': 'Total',
    'col.paid': 'Paid',
    'col.paymentDate': 'Payment Date',
    'col.mode': 'Mode',
    'col.remarks': 'Remarks',
    'col.user': 'User',
    'col.email': 'Email',
    'col.role': 'Role',
    'col.loginAt': 'Login At',
    'col.details': 'Details',
    'col.at': 'At',
    'col.fixedSalary': 'Fixed Salary',
    'col.commissionPercent': 'Commission %',
    'col.contact': 'Contact',
    'col.month': 'Month',
    'col.base': 'Base',
    'col.commission': 'Commission',
    'col.advances': 'Advances',
    'col.deductions': 'Deductions',
    'col.netSalary': 'Net salary',
    'col.paidTotal': 'Paid (total)',
    'col.remaining': 'Remaining',
    'col.creditSalesTotal': 'Credit sales (total)',
    'col.receivablesOpen': 'Receivables (open)',
    'col.received': 'Received',
    'col.credit': 'Credit',
    'col.discount': 'Discount',
    'col.returns': 'Returns',
    'col.locked': 'Locked',
    'col.bankAccounts': 'Bank (accounts)',
    'col.totalBankSales': 'Total bank sales',
  },
  ur: {
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.branches': 'برانچز',
    'nav.banks': 'بینکس',
    'nav.inventory': 'انوینٹری',
    'nav.suppliers': 'سپلائرز',
    'nav.staff': 'سٹاف، سیلری، رینٹ اور بلز',
    'nav.sales': 'سیلز',
    'nav.receivables': 'ریسیویبلز',
    'nav.purchases': 'پرچیزز',
    'nav.payments': 'پیمنٹس',
    'nav.reports': 'رپورٹس اور اینالیٹکس',
    'nav.users': 'یوزرز اور رولز',
    'nav.settings': 'سیٹنگز',
    'page.dashboard.title': 'ڈیش بورڈ',
    'page.branches.title': 'برانچ مینجمنٹ',
    'page.banks.title': 'بینک مینجمنٹ',
    'page.inventory.title': 'انوینٹری',
    'page.suppliers.title': 'سپلائرز',
    'page.staff.title': 'سٹاف، سیلری، رینٹ اور بلز',
    'page.sales.title': 'سیلز مینجمنٹ',
    'page.receivables.title': 'ریسیویبلز (کریڈٹ سیلز)',
    'page.purchases.title': 'پرچیز مینجمنٹ',
    'page.payments.title': 'پیمنٹس',
    'page.reports.title': 'رپورٹس اور اینالیٹکس',
    'page.users.title': 'یوزرز اور رولز',
    // Dashboard cards
    'dashboard.card.salesToday': 'آج کی سیلز',
    'dashboard.card.salesTodayCash': 'آج کی کیش سیلز',
    'dashboard.card.salesTodayBank': 'آج کی بینک سیلز',
    'dashboard.card.salesTodayCredit': 'آج کی کریڈٹ سیلز',
    'dashboard.card.salesOnCredit': 'کریڈٹ سیلز (ریسیویبل)',
    'dashboard.card.receivableRecovered': 'ریسیویبل کی وصولیاں (کل)',
    'dashboard.card.salesMonth': 'سیلز (مہینہ)',
    'dashboard.card.salesMonthCash': 'کیش سیلز (مہینہ)',
    'dashboard.card.salesMonthBank': 'بینک سیلز (مہینہ)',
    'dashboard.card.netProfitMonth': 'خالص منافع (مہینہ)',
    'dashboard.card.cashInHand': 'کیش اِن ہینڈ',
    'dashboard.card.bankBalance': 'بینک بیلنس',
    'dashboard.card.payables': 'پی ایبلز',
    'dashboard.card.rentBillsPayable': 'کل کرایہ اور بلز قابلِ ادائیگی',
    'dashboard.card.salariesPayable': 'کل تنخواہیں قابلِ ادائیگی',
    'dashboard.card.totalPaidAll': 'کل ادا شدہ (سب)',
    // Generic column labels
    'col.code': 'کوڈ',
    'col.name': 'نام',
    'col.location': 'مقام',
    'col.manager': 'منیجر',
    'col.openingClosing': 'اوپننگ / کلوزنگ',
    'col.status': 'اسٹیٹس',
    'col.actions': 'کاروائیاں',
    'col.date': 'تاریخ',
    'col.type': 'قسم',
    'col.amount': 'رقم',
    'col.reference': 'حوالہ',
    'col.description': 'تفصیل',
    'col.branch': 'برانچ',
    'col.accountNumber': 'اکاؤنٹ نمبر',
    'col.balance': 'بیلنس',
    'col.product': 'پروڈکٹ',
    'col.soldQuantity': 'فروخت شدہ تعداد',
    'col.unitPrice': 'یونٹ قیمت',
    'col.total': 'کل',
    'col.totalQuantitySold': 'کل فروخت شدہ تعداد',
    'col.totalAmount': 'کل رقم',
    'col.address': 'ایڈریس',
    'col.phone': 'فون',
    'col.vatNumber': 'وی اے ٹی نمبر',
    'col.pendingBalance': 'باقی بیلنس',
    'col.invoice': 'انوائس',
    'col.dueDate': 'آخری تاریخ',
    'col.totalPurchases': 'کل خریداری',
    'col.paid': 'ادا شدہ',
    'col.paymentDate': 'ادائیگی کی تاریخ',
    'col.mode': 'موڈ',
    'col.remarks': 'ریمارکس',
    'col.user': 'یوزر',
    'col.email': 'ای میل',
    'col.role': 'رول',
    'col.loginAt': 'لاگ اِن وقت',
    'col.details': 'تفصیل',
    'col.at': 'وقت',
    'col.fixedSalary': 'فکس سیلری',
    'col.commissionPercent': 'کمیشن %',
    'col.contact': 'رابطہ',
    'col.month': 'مہینہ',
    'col.base': 'بنیادی',
    'col.commission': 'کمیشن',
    'col.advances': 'ایڈوانسز',
    'col.deductions': 'کٹوتیاں',
    'col.netSalary': 'نیٹ سیلری',
    'col.paidTotal': 'کل ادا شدہ',
    'col.remaining': 'باقی',
    'col.creditSalesTotal': 'کریڈٹ سیلز (کل)',
    'col.receivablesOpen': 'ریسیویبلز (اوپن)',
    'col.received': 'وصول شدہ',
    'col.credit': 'کریڈٹ',
    'col.discount': 'ڈسکاؤنٹ',
    'col.returns': 'ریٹرنز',
    'col.locked': 'لاکڈ',
    'col.bankAccounts': 'بینک (اکاؤنٹس)',
    'col.totalBankSales': 'کل بینک سیلز',
  },
  ar: {
    'nav.dashboard': 'لوحة التحكم',
    'nav.branches': 'الفروع',
    'nav.banks': 'البنوك',
    'nav.inventory': 'المخزون',
    'nav.suppliers': 'الموردون',
    'nav.staff': 'الموظفون والرواتب والإيجار والفواتير',
    'nav.sales': 'المبيعات',
    'nav.receivables': 'المديونيات',
    'nav.purchases': 'المشتريات',
    'nav.payments': 'المدفوعات',
    'nav.reports': 'التقارير والتحليلات',
    'nav.users': 'المستخدمون والصلاحيات',
    'nav.settings': 'الإعدادات',
    'page.dashboard.title': 'لوحة التحكم',
    'page.branches.title': 'إدارة الفروع',
    'page.banks.title': 'إدارة البنوك',
    'page.inventory.title': 'المخزون',
    'page.suppliers.title': 'الموردون',
    'page.staff.title': 'الموظفون والرواتب والإيجار والفواتير',
    'page.sales.title': 'إدارة المبيعات',
    'page.receivables.title': 'المديونيات (مبيعات آجلة)',
    'page.purchases.title': 'إدارة المشتريات',
    'page.payments.title': 'المدفوعات',
    'page.reports.title': 'التقارير والتحليلات',
    'page.users.title': 'المستخدمون والصلاحيات',
    // Dashboard cards
    'dashboard.card.salesToday': 'مبيعات اليوم',
    'dashboard.card.salesTodayCash': 'مبيعات اليوم نقدًا',
    'dashboard.card.salesTodayBank': 'مبيعات اليوم عبر البنك',
    'dashboard.card.salesTodayCredit': 'مبيعات اليوم بالآجل',
    'dashboard.card.salesOnCredit': 'مبيعات بالآجل (مديونيات)',
    'dashboard.card.receivableRecovered': 'تحصيلات المديونيات (الإجمالي)',
    'dashboard.card.salesMonth': 'مبيعات (الشهر)',
    'dashboard.card.salesMonthCash': 'مبيعات نقدية (الشهر)',
    'dashboard.card.salesMonthBank': 'مبيعات بنكية (الشهر)',
    'dashboard.card.netProfitMonth': 'صافي الربح (الشهر)',
    'dashboard.card.cashInHand': 'النقد المتاح',
    'dashboard.card.bankBalance': 'رصيد البنك',
    'dashboard.card.payables': 'المدفوعات المستحقة',
    'dashboard.card.rentBillsPayable': 'إجمالي الإيجار والفواتير المستحقة',
    'dashboard.card.salariesPayable': 'إجمالي الرواتب المستحقة',
    'dashboard.card.totalPaidAll': 'إجمالي المدفوع (الكل)',
    // Generic column labels
    'col.code': 'الرمز',
    'col.name': 'الاسم',
    'col.location': 'الموقع',
    'col.manager': 'المدير',
    'col.openingClosing': 'الافتتاح / الإغلاق',
    'col.status': 'الحالة',
    'col.actions': 'الإجراءات',
    'col.date': 'التاريخ',
    'col.type': 'النوع',
    'col.amount': 'المبلغ',
    'col.reference': 'المرجع',
    'col.description': 'الوصف',
    'col.branch': 'الفرع',
    'col.accountNumber': 'رقم الحساب',
    'col.balance': 'الرصيد',
    'col.product': 'المنتج',
    'col.soldQuantity': 'الكمية المباعة',
    'col.unitPrice': 'سعر الوحدة',
    'col.total': 'الإجمالي',
    'col.totalQuantitySold': 'إجمالي الكمية المباعة',
    'col.totalAmount': 'إجمالي المبلغ',
    'col.address': 'العنوان',
    'col.phone': 'الهاتف',
    'col.vatNumber': 'رقم الضريبة',
    'col.pendingBalance': 'الرصيد المتبقي',
    'col.invoice': 'الفاتورة',
    'col.dueDate': 'تاريخ الاستحقاق',
    'col.totalPurchases': 'إجمالي المشتريات',
    'col.paid': 'المدفوع',
    'col.paymentDate': 'تاريخ الدفع',
    'col.mode': 'طريقة الدفع',
    'col.remarks': 'ملاحظات',
    'col.user': 'المستخدم',
    'col.email': 'البريد الإلكتروني',
    'col.role': 'الدور',
    'col.loginAt': 'وقت الدخول',
    'col.details': 'التفاصيل',
    'col.at': 'في',
    'col.fixedSalary': 'الراتب الثابت',
    'col.commissionPercent': 'العمولة %',
    'col.contact': 'التواصل',
    'col.month': 'الشهر',
    'col.base': 'الأساسي',
    'col.commission': 'العمولة',
    'col.advances': 'السُلف',
    'col.deductions': 'الاستقطاعات',
    'col.netSalary': 'صافي الراتب',
    'col.paidTotal': 'إجمالي المدفوع',
    'col.remaining': 'المتبقي',
    'col.creditSalesTotal': 'المبيعات الآجلة (الإجمالي)',
    'col.receivablesOpen': 'المديونيات (مفتوحة)',
    'col.received': 'المحصلة',
    'col.credit': 'دَين',
    'col.discount': 'خصم',
    'col.returns': 'مرتجعات',
    'col.locked': 'مؤمَّن',
    'col.bankAccounts': 'البنك (الحسابات)',
    'col.totalBankSales': 'إجمالي مبيعات البنك',
  },
};

function translate(lang, key) {
  const dict = MESSAGES[lang] || MESSAGES.en;
  return dict[key] || MESSAGES.en[key] || key;
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    let cancelled = false;
    api
      .get('/settings/language')
      .then((res) => {
        const v = res?.value || res?.language;
        if (!cancelled && typeof v === 'string' && v.trim()) {
          setLanguage(v);
        }
      })
      .catch(() => {
        // ignore, default to 'en'
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key) => translate(language, key),
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}

